import "./globals.css";
import Section from "@/components/Home/Section";
import Footer from "@/components/Footer";
import ScrollProvider from "@/components/ScrollProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ScrollProvider>
          <Section data-scroll-section />
          {children}
          <Footer data-scroll-section />
        </ScrollProvider>
      </body>
    </html>
  );
}
